import re


class AddNotifyTransformer:
    """
    Transforms deprecated:

        addNotify(DropTargetContextPeer)

    into a Java 21 compatible DropTarget setup method.
    """

    def transform(self, content: str):

        changes = []

        # ---------------------------------------------------------
        # Skip files that don't use addNotify()
        # ---------------------------------------------------------
        if "addNotify(" not in content:
            return content, changes

        # ---------------------------------------------------------
        # Add required imports AFTER package declaration
        # ---------------------------------------------------------
        imports_to_add = (
            "import java.awt.*;\n"
            "import java.awt.dnd.*;\n"
        )

        if "import java.awt.dnd" not in content:

            package_match = re.search(
                r'^\s*package\s+.*?;\s*$',
                content,
                re.MULTILINE
            )

            if package_match:

                insert_pos = package_match.end()

                content = (
                    content[:insert_pos]
                    + "\n\n"
                    + imports_to_add
                    + content[insert_pos:]
                )

            else:

                content = imports_to_add + "\n" + content

            changes.append("Added AWT DnD imports")

        # ---------------------------------------------------------
        # Locate class
        # ---------------------------------------------------------

        class_pattern = r'class\s+\w+[^{]*\{'

        class_match = re.search(class_pattern, content)

        if not class_match:
            return content, changes

        insert_pos = class_match.end()

        # ---------------------------------------------------------
        # Replace addNotify(DropTargetContextPeer)
        # ---------------------------------------------------------

        method_pattern = (
            r'(@\w+(?:\([^)]*\))?\s*)*'
            r'(public|protected)\s+void\s+'
            r'addNotify\s*'
            r'\(\s*DropTargetContextPeer\s+\w+\s*\)'
            r'\s*\{([\s\S]*?)\}'
        )

        method_matches = list(re.finditer(method_pattern, content))

        for match in reversed(method_matches):

            method_body = match.group(3).strip()

            content = (
                content[:match.start()]
                + content[match.end():]
            )

            if method_body == "":

                changes.append(
                    "Removed empty addNotify()"
                )

                continue

            new_method = f"""

    // ==========================================================
    // Auto-generated by Java 8 → Java 21 Transformer
    // Replaces deprecated addNotify(DropTargetContextPeer)
    // ==========================================================

    public void setupDropTarget(java.awt.Component component) {{

        DropTarget dt = new DropTarget(
            component,
            new DropTargetListener() {{

                @Override
                public void dragEnter(DropTargetDragEvent dtde) {{
                }}

                @Override
                public void dragOver(DropTargetDragEvent dtde) {{
                }}

                @Override
                public void dropActionChanged(DropTargetDragEvent dtde) {{
                }}

                @Override
                public void dragExit(DropTargetEvent dte) {{
                }}

                @Override
                public void drop(DropTargetDropEvent dtde) {{

                    // Original addNotify() logic

                    {method_body}

                }}
            }}
        );
    }}

"""

            content = (
                content[:insert_pos]
                + new_method
                + content[insert_pos:]
            )

            changes.append(
                "Replaced addNotify() with setupDropTarget(Component)"
            )

        # ---------------------------------------------------------
        # Replace deprecated calls
        # ---------------------------------------------------------

        call_pattern = (
            r'(\b\w+\b)\.addNotify\s*\((.*?)\)\s*;'
        )

        call_matches = list(re.finditer(call_pattern, content))

        for match in reversed(call_matches):

            replacement = (
                "\n"
                "        // TODO(Java21)\n"
                "        // Deprecated addNotify() call removed.\n"
                "        // Invoke setupDropTarget(component) if required.\n"
            )

            content = (
                content[:match.start()]
                + replacement
                + content[match.end():]
            )

            changes.append(
                "Removed deprecated addNotify() call"
            )

        return content, changes